[#2dmz3hj] Header
nfach98/majoo_mini_project_1 pull request #3
Opened 2022-03-11 13:32 UTC by vstacked

## Description
Adding header widget using assets svg for image & icon.
- add ui for portrait & landscape (base on scratch image on clickUp)

## Type of Change

- [x] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

## Evidence
<img src="https://user-images.githubusercontent.com/54944887/157877217-7c2e8a75-2cb4-410f-b7e0-da1eb4522fff.png" height="300"> <img src="https://user-images.githubusercontent.com/54944887/157877233-82ca463f-7609-4241-9cb6-4208a73ad515.png" height="300">

2022-03-13 12:39 UTC, nfach98 approved these changes

2022-03-13 12:39 UTC, nfach98 commented on lib/page/home/widget/header.dart
> +    final width = MediaQuery.of(context).size.width;
Opsional, untuk width bisa dijadikan parameter widget

2022-03-14 06:36 UTC, isa9x approved these changes

2022-03-14 07:17 UTC, StanislausPN approved these changes

2022-03-14 07:18 UTC, StanislausPN approved these changes

2022-03-14 07:50 UTC, mnafian requested changes

2022-03-14 07:50 UTC, mnafian commented on lib/page/home/widget/header.dart
> +    final width = this.width ?? MediaQuery.of(context).size.width;
karena MediaQuery di pake di banyak tempat, consider dibuat ext seperti yg aku contohkan keamaren biar tidak terlalu banyak deklarasi ulang

2022-03-14 07:50 UTC, mnafian commented on lib/page/home/widget/header.dart
> +                children: <Widget>[
opsional, di sdk existing yg dipake harusnya secara implisit tanpa declare <widget> udah bisa, ini dihapus aja sama yg dibawah2

2022-03-14 08:03 UTC, vstacked commented on lib/page/home/widget/header.dart
> +                children: <Widget>[
berarti ngga pake `crossAxisAlignment` sama `mainAxisAlignment` mas? itu saya pake buat positioning text & button widget biar kebawah

2022-03-14 08:10 UTC, vstacked commented on lib/page/home/widget/header.dart
> +                children: <Widget>[
ohh baik mas

2022-03-14 08:10 UTC, mnafian commented on lib/page/home/widget/header.dart
> +                children: <Widget>[
updated comment ya, somehow kalo aku nulis `<widget>` gak bisa di render sama comment github kalo gak format as markdown, maksudnya hapus widget declarationnya aja

2022-03-14 08:14 UTC, mnafian approved these changes

2022-03-14 08:17 UTC, vstacked commented on lib/page/home/widget/header.dart
> +                children: <Widget>[
oalahh, iya mas

2022-03-14 10:29 UTC, merged