2 - Text Content
nfach98/majoo_mini_project_1 pull request #7
Opened 2022-03-12 09:24 UTC by isa9x

Penambahan text content di halaman detail, dan beberapa konstant

cara pakai:
![image](https://user-images.githubusercontent.com/10303178/158012247-96638715-a439-4779-8bdc-baead890862a.png)

screenshot potrait:
![image](https://user-images.githubusercontent.com/10303178/158012263-8fa0753b-016d-4140-9073-2eb5f15ff016.png)

screenshot landscape:
![image](https://user-images.githubusercontent.com/10303178/158012271-fd6dabbd-cf0f-4153-ae7b-1bda5ba0ca54.png)

2022-03-12 14:34 UTC, vstacked approved these changes

2022-03-13 12:44 UTC, nfach98 approved these changes
Good

2022-03-14 07:16 UTC, StanislausPN approved these changes

2022-03-14 10:20 UTC, mnafian requested changes

2022-03-14 10:20 UTC, mnafian commented on lib/page/detail/widget/detail_slider.dart
> +                        ? Container(
di extract aja jadikan function return sebuah widget biar gak kepanjangan ada ternary opetator buat conditon gini.

2022-03-14 11:40 UTC, isa9x commented on lib/page/detail/widget/detail_slider.dart
> +                        ? Container(
ini saya perbaiki di branch images_slider mas

2022-03-15 00:02 UTC, isa9x commented on lib/page/detail/widget/detail_slider.dart
> +                        ? Container(
sekalian juga saya upload disini mas

2022-03-15 06:39 UTC, mnafian approved these changes

2022-03-15 07:03 UTC, merged