2 - Counter Quantity [#2dmz47h]
nfach98/majoo_mini_project_1 pull request #8
Opened 2022-03-12 09:29 UTC by isa9x

Penambahan widget content quantity

cara pakai:
![image](https://user-images.githubusercontent.com/10303178/158012439-3bee5fc7-991d-4c40-aefc-b80c1e7e7b2f.png)

Screenshot Potrait:
![image](https://user-images.githubusercontent.com/10303178/158012463-cabb3ad4-47bd-46d5-a29f-dae110149b11.png)

Screenshot Landscape:
![image](https://user-images.githubusercontent.com/10303178/158012476-d0cb69b1-30e6-4c11-99d5-60687953bbb5.png)

2022-03-12 14:40 UTC, vstacked commented on lib/page/detail/widget/detail_counter.dart
> +        ),
dibikin internal widget mungkin mas? buat yang decrease sama increase biar ngga duplikasi

2022-03-13 12:44 UTC, nfach98 approved these changes
Good

2022-03-14 05:49 UTC, vstacked approved these changes

2022-03-14 10:24 UTC, mnafian requested changes

2022-03-14 10:24 UTC, mnafian commented on lib/page/detail/widget/detail_slider.dart
> +                        ? Container(
ini di extract jadi function widget diluar build method biar gak terlalu kompleks ternary operatornya

2022-03-14 11:35 UTC, StanislausPN approved these changes

2022-03-14 11:35 UTC, StanislausPN commented on lib/page/detail/widget/detail_counter.dart
> +            child: TextField(
Mau tanya mas, kenapa dibuat textfield?

2022-03-14 11:35 UTC, StanislausPN commented on lib/page/detail/widget/detail_content.dart
> +              top: screenHeight * 0.05,
menurutku untuk padding dan height width, jangan dikasih media query mas, mending di paten saja sesuai ukuran di figma. Dulu pernah pengalaman dibikin seperti ini, ketika dia ambil layar besar, ukurannya jadi memanjang.

2022-03-14 11:48 UTC, isa9x commented on lib/page/detail/widget/detail_slider.dart
> +                        ? Container(
ini saya perbaiki di branch images_slider juga ya mas, 
![image](https://user-images.githubusercontent.com/10303178/158166022-2a99de48-f3f4-4ae1-8142-1979095bbcb6.png)

2022-03-14 11:50 UTC, isa9x commented on lib/page/detail/widget/detail_counter.dart
> +            child: TextField(
yang pertama terlintas pakai Textfield saya mas, mungkin ada saran yang lebih baik mas?

2022-03-15 06:49 UTC, mnafian approved these changes

2022-03-15 06:49 UTC, mnafian commented on lib/page/detail/widget/detail_slider.dart
> +                        ? Container(
ini di extract jadi function widget diluar build method biar gak terlalu kompleks ternary operatornya

2022-03-15 07:18 UTC, StanislausPN approved these changes

2022-03-15 07:22 UTC, merged